name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install
          npm cache clean --force
          npm list
          node -v
          npm -v
      
      - name: Build
        run: |
          rm -rf dist
          NODE_ENV=production npm run build
          echo "Build completed. Checking dist directory:"
          ls -la dist || echo "dist directory not found"
          echo "Checking dist/assets directory:"
          ls -la dist/assets || echo "dist/assets directory not found"
          echo "Checking index.html:"
          cat dist/index.html || echo "index.html not found"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Automatically inject base path in your index.html
          static_site_generator: vite
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 